# Generated by Django 5.2.8 on 2025-12-07 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    Category = apps.get_model('quiz', 'Category')
    Category.objects.get_or_create(name="General")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create Category table
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),

        # 2. Create default Category using data migration
        migrations.RunPython(create_default_category),

        # 3. Add category ForeignKey to Question (no default string, will use default category ID)
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='quiz.category',
                null=True,  # Temporary null to allow migration
            ),
        ),

        # 4. Create QuizAttempt model
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-date_taken'],
            },
        ),

        # 5. Create UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # 6. Delete old QuizScore model
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
